# Generated by Django 4.2 on 2023-04-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('family', models.CharField(max_length=20, verbose_name='فامیلی')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
            ],
            options={
                'verbose_name': 'مشخصات ',
                'verbose_name_plural': 'مشخصات کاربران',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
